### PR TITLE
Showflake v2.2.2 upgrade from str 2287

### PR DESCRIPTION
**Pull request by wrehman-skap**

### CODE REVIEW

**Comment by JonathonO** [comment]
@wrehman-skap other than the merge of the Snowflake 2.2.2 changes, have you contributed any code changes in this PR? Since your commits are only the merge commits, I can't tell just based on the commit history.

**Comment by wrehman-skap** [comment]
> @wrehman-skap other than the merge of the Snowflake 2.2.2 changes, have you contributed any code changes in this PR? Since your commits are only the merge commits, I can't tell just based on the commit history.

@JonathonO Only resolved some conflicts, I haven't made any other changes to code base, our all streamkap tests were working fine, so changes were not needed.

**Comment by JonathonO** [comment]
@wrehman-skap did you find any Snowflake specific Connector config property changes between our current version and this latest version? If so, we may need to update our Snowflake setup documentation.

**Comment by wrehman-skap** [comment]
@JonathonO there were some addition of config in SnowflakeSinkConnectorConfig, all existing config were stayed the same.

**Comment by JonathonO** [comment]
> @JonathonO there were some addition of config in SnowflakeSinkConnectorConfig, all existing config were stayed the same.

@wrehman-skap what were the additions?

**Comment by acristu** [comment]
@wrehman-skap can we close this one? the dynamic tables PR includes this one also, right ?

**Comment by wrehman-skap** [comment]
> @wrehman-skap can we close this one? the dynamic tables PR includes this one also, right ?

Yes, we can close that one

**Pull request merged**
