### PR TITLE
Eng 442 dynamic table handle reserve keywords

### PR DESCRIPTION
**Pull request by wrehman-skap**

### CODE REVIEW

**Review by JonathonO — COMMENTED** [review]
@wrehman-skap Snowflake has a utility function called `quoteNameIfNeeded` I believe which adds quotes and uppercases names if needed (https://github.com/snowflakedb/snowflake-kafka-connector/pull/693).

May be a good idea to use that in place of hardcoded quotes?

Another consideration: in upcoming Source mappings, if a table name has invalid characters (according to Avro's special character limitations), it will replace them with underscores. I'm not sure how that will impact your work?

**Comment by wrehman-skap** [comment]
> @wrehman-skap Snowflake has a utility function called `quoteNameIfNeeded` I believe which adds quotes and uppercases names if needed ([snowflakedb#693](https://github.com/snowflakedb/snowflake-kafka-connector/pull/693)).
> 
> May be a good idea to use that in place of hardcoded quotes?
> 
> Another consideration: in upcoming Source mappings, if a table name has invalid characters (according to Avro's special character limitations), it will replace them with underscores. I'm not sure how that will impact your work?

@JonathonO  in script we are using table name in different ways, so we can't inject double quoted value, as same is using in object name as well like `{{tableName}}_CT`. For same reason we have to make sure when `SchematizationUtils` calls template and passes table name, it should not contain any double quote.

I don't think underscores will cause any issues.

**Comment by JonathonO** [comment]
> > @wrehman-skap Snowflake has a utility function called `quoteNameIfNeeded` I believe which adds quotes and uppercases names if needed ([snowflakedb#693](https://github.com/snowflakedb/snowflake-kafka-connector/pull/693)).
> > May be a good idea to use that in place of hardcoded quotes?
> > Another consideration: in upcoming Source mappings, if a table name has invalid characters (according to Avro's special character limitations), it will replace them with underscores. I'm not sure how that will impact your work?
> 
> @JonathonO in script we are using table name in different ways, so we can't inject double quoted value, as same is using in object name as well like `{{tableName}}_CT`. For same reason we have to make sure when `SchematizationUtils` calls template and passes table name, it should not contain any double quote.
> 
> I don't think underscores will cause any issues.

@wrehman-skap at what point are you quoting it? On table create only?

**Comment by wrehman-skap** [comment]
> > > @wrehman-skap Snowflake has a utility function called `quoteNameIfNeeded` I believe which adds quotes and uppercases names if needed ([snowflakedb#693](https://github.com/snowflakedb/snowflake-kafka-connector/pull/693)).
> > > May be a good idea to use that in place of hardcoded quotes?
> > > Another consideration: in upcoming Source mappings, if a table name has invalid characters (according to Avro's special character limitations), it will replace them with underscores. I'm not sure how that will impact your work?
> > 
> > 
> > @JonathonO in script we are using table name in different ways, so we can't inject double quoted value, as same is using in object name as well like `{{tableName}}_CT`. For same reason we have to make sure when `SchematizationUtils` calls template and passes table name, it should not contain any double quote.
> > I don't think underscores will cause any issues.
> 
> @wrehman-skap at what point are you quoting it? On table create only?

Yes, we are injecting table name to Mustache.java for place holders, as you can see in below script, it is used in multiple places i.e. DT/CT object creation and as table reference.
```
"create.sql.execute": "CREATE OR REPLACE DYNAMIC TABLE {{table}}_DT TARGET_LAG='{{targetLag}} minutes' WAREHOUSE={{warehouse}} AS SELECT * FROM( SELECT *, ROW_NUMBER() OVER (PARTITION BY {{primaryKeyColumns}} ORDER BY _streamkap_ts_ms DESC) AS dedupe_id FROM \"{{table}}\" ) WHERE dedupe_id = 1 AND __deleted = 'false';CREATE OR REPLACE TASK {{table}}_CT WAREHOUSE={{warehouse}} SCHEDULE='{{schedule}} minutes' TASK_AUTO_RETRY_ATTEMPTS=3 ALLOW_OVERLAPPING_EXECUTION=FALSE AS DELETE FROM \"{{table}}\" WHERE NOT EXISTS ( SELECT 1 FROM ( SELECT {{primaryKeyColumns}}, MAX(_streamkap_ts_ms) AS max_timestamp FROM \"{{table}}\" GROUP BY {{primaryKeyColumns}} ) AS subquery WHERE {{{keyColumnsAndCondition}}} AND \"{{table}}\"._streamkap_ts_ms = subquery.max_timestamp);ALTER TASK {{table}}_CT RESUME",
```

**Comment by JonathonO** [comment]
@wrehman-skap so there's no issues with the original, unquoted table name (which may contain special characters or be a reserved keyword) being used elsewhere in the code that you know of/your test cases have picked up?

@JonathonO SF connector handles them itself, so creating table etc is not an issue, only issue was on our custom SQL script as it has to handle those use cases as well, SF converts reserve keywords to uppercase and in double quotes. 
We also using SF util to get tablename  `String tableName = Utils.generateValidName(topicName, topic2table);` to make sure we are using valid table name according to SF.

**Comment by wrehman-skap** [comment]
@JonathonO Actually we can replace hard code double quotes in `keyColumnsAndCondition` placeholder to `v-> Utils.quoteNameIfNeeded(tableName) +"."+v+" = subquery."+v` if that was you original request ?

**Comment by JonathonO** [comment]
> @JonathonO Actually we can replace hard code double quotes in `keyColumnsAndCondition` placeholder to `v-> Utils.quoteNameIfNeeded(tableName) +"."+v+" = subquery."+v` if that was you original request ?

I'd do it even if it's always going to quote the table name. Means that, in the future, if we realise we don't need quotes, we run less risk of missing some hardcoded quotes in our codebase.

**Comment by wrehman-skap** [comment]
@JonathonO above changes were pushed as well.

**Review by JonathonO — APPROVED** [review]

**Pull request merged**
