### PR TITLE
STR-2507

### PR DESCRIPTION
**Pull request by EduardHantig**
…e - Quoting identifier issue

### CODE REVIEW

**Comment by EduardHantig** [comment]
@JonathonO @acristu More than half of the tests are failing. Though, they are not related to this change. Same are failing also on  streamkap-main branch.

**Comment by JonathonO** [comment]
@EduardHantig did you see this https://github.com/snowflakedb/snowflake-kafka-connector/pull/693? 

We haven't merged their v2.1.2 changes into our fork yet but, please compare and review the quoting / special character handling code.

**Comment by EduardHantig** [comment]
@JonathonO Didn't notice that. 

I had a look on it and their solution is similar, i.e. creating a new method in Utils to be used for handling special characters or conflicts with reserved keywords. 

Differently, though, they decided to go only for schematization changes. Their strategy was to use double quotes and keep uppercase in every situation - which actually seems good idea - to be in sync with snowflake uppercase naming convention. Using double quotes everytime is also much safer for future unhandled cases.

Still, as far as I understand from the commits and comments, any other query not used in a schematization change will not benefit of this fix, which is odd...

On my side, I changed the service to use double quotes in every situation where identifiers uses special character, not only for schematization queries and usage of double quotes is returned only when the SQL identifier is not considered a "simple SQL identifier" in alignment with SQL standard. 

Re-iterating - is safer to use double quotes every time for identifiers, of course, but maybe also good to extend the usage, not keeping it only for schematization queries. Good to keep uppercase for identifiers too. 

We can go for two approaches:
1. Pick their commit and test with these already changes.
2. Keep my PR and making similar to theirs, perform:
- Change to go for double quotes every time;
- Change to go for uppercase everytime.
- But keep changes for entire service (propagated to all of its usage), not only schematization.

I can make the changes accordingly. What do you think?

**Comment by acristu** [comment]
@EduardHantig @JonathonO  this is the test I am usually depending on to test stuff: https://github.com/streamkap-com/snowflake-kafka-connector/pull/13
Just added debezium date field to this test ...

**Comment by JonathonO** [comment]
@EduardHantig I don't know the Snowflake codebase super well, but shouldn't we also be updating SchematizationUtils or at least making some changes to internal/streaming code and the RecordService?

Feels like we're missing something in our changes.

Could also do with following up on Alex's reminder about the testing code. What's going to be the impact (if any) to existing Sinks if this is deployed?

**Comment by EduardHantig** [comment]
@JonathonO I also don't know their code super well.

However, `SchematizationUtils` uses the ConnectionService which I changed (i.e. `SnowflakeConnectionServiceV1`). 

As I modified this connectionService as a general change, I let all other classes unchanged (internal/streaming) to work as they did previously, including RecordService. 

I guess they changed RecordService for propagating the change to queries not included in Schematization changes. Still, they addressed only the columnName as identifier... 

@acristu In order to run that test I need privateKey and passphrasefor accessing snowflake.

```
conf.put(Utils.SF_PRIVATE_KEY, System.getenv("SNOWFLAKE_KEY"));
conf.put(Utils.PRIVATE_KEY_PASSPHRASE, System.getenv("SNOWFLAKE_KEY_PASS"));
```

**Comment by EduardHantig** [comment]
@JonathonO @acristu I was also thinking that since we may need to upgrade to a new version of snowflake, because of the the tracking partner feature, we can just upgrade to 2.1.2 which includes the identifier fix (even if it's just for column name - but error thrown was related to column naming). So for now should work and fix the consumer blockage.

**Comment by JonathonO** [comment]
> @JonathonO @acristu I was also thinking that since we may need to upgrade to a new version of snowflake, because of the the tracking partner feature, we can just upgrade to 2.1.2 which includes the identifier fix (even if it's just for column name - but error thrown was related to column naming). So for now should work and fix the consumer blockage.

You can try, yes. Needs to be done as soon as possible as it'll need testing.

**Comment by EduardHantig** [comment]
@JonathonO 
Ok, will try to pull and solve the conflicts between the v2.1.2 branch and our branch and make a PR for review asap

**Comment by EduardHantig** [comment]
@acristu @JonathonO 
Here is the PR for upgrading to 2.1.2 - https://github.com/streamkap-com/snowflake-kafka-connector/pull/17

There were lots of changes and therefore conflicts... Build is failing at compile time because of the two streamkap IT. 
`SnowflakeStreamkapSinkIT`
`StreamkapITSnowflake`

Beyond that, As I said also before, same tests failing in streamkap-main are red also here.

**Pull request closed without merging**
