### PR TITLE
Upgrade to version 1.9.2

### PR DESCRIPTION
**Pull request by JonathonO**
Merge of upstream changes into our fork and main branch.

DataDog logs showing warnings since 1.9.2 release. Doesn't seem to impact the Sink - for now.

```
[SF_KAFKA_CONNECTOR] [KC:1822887634] Connector update is available, please upgrade Snowflake Kafka Connector (1.9.1 -> 1.9.2)
```

**Note:** Resolved conflicts on our auto schematization config option changes

### CODE REVIEW

**Comment by JonathonO** [comment]
Revert and squash commit

**Comment by JonathonO** [comment]
@acristu still needs to be built and tested but please review the upstream merge for me.

**Review by acristu — APPROVED** [review]
looks good to me, streamkap changes seem to not be affected ... needs testing with regexps in topic2table, no auto schematization, etc... if not already done

**Comment by JonathonO** [comment]
@acristu covered by PR #3 so closing this one

**Pull request closed without merging**
